HandsomeSalgu/VPLAY-pocopoco

- src/main/java/pocopoco_vplay/Board/controller/BoardController.java
- src/main/java/pocopoco_vplay/Board/exception/BoardException.java
- src/main/java/pocopoco_vplay/Board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/Board/model/service/BoardService.java
- src/main/java/pocopoco_vplay/Board/model/vo/Board.java
- src/main/resources/templates/views/board/content/all_menu.html
- src/main/resources/templates/views/footer.html
> 250214 board 이름 수정 및 html 추가

- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/java/pocopoco_vplay/board/model/vo/Board.java
- src/main/java/pocopoco_vplay/board/model/vo/Content.java
- src/main/java/pocopoco_vplay/board/model/vo/File.java
- src/main/java/pocopoco_vplay/board/model/vo/Reply.java
- src/main/java/pocopoco_vplay/payment/controller/PaymentController.java
- src/main/java/pocopoco_vplay/payment/exception/PaymentException.java
- src/main/java/pocopoco_vplay/payment/model/mapper/PaymentMapper.java
- src/main/java/pocopoco_vplay/payment/model/service/PaymentService.java
- src/main/java/pocopoco_vplay/payment/model/vo/Payment.java
- src/main/java/pocopoco_vplay/reply/controller/ReplyController.java
- src/main/java/pocopoco_vplay/reply/exception/ReplyException.java
- src/main/java/pocopoco_vplay/reply/model/mapper/ReplyMapper.java
- src/main/java/pocopoco_vplay/reply/model/service/ReplyService.java
- src/main/java/pocopoco_vplay/reply/model/vo/Reply.java
> 250217 vo및 controller 추가

- src/main/java/pocopoco_vplay/users/model/mapper/UsersMapper.java
usersmapper 자바클래스 - > 인터페이스로 변경
> usersmapper 자바클래스 - > 인터페이스로 변경

- src/main/resources/mappers/users-mapper.xml
UsersMapper 추가 및 아이디 중복확인 쿼리 작성
> UsersMapper 추가 및 아이디 중복확인 쿼리 작성

- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/resources/templates/index.html
- src/main/resources/templates/views/users/signup.html
> 250217 템플릿 오류

- src/main/java/pocopoco_vplay/commom/TemplateResolverConfig.java
> 250217 템플릿 리졸브 오류 수정

- src/main/java/pocopoco_vplay/commom/config/SecurityConfig.java
- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/java/pocopoco_vplay/users/exception/UsersException.java
> SecurityConfig 생성 및 로그인 구현중

- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/java/pocopoco_vplay/users/model/service/UsersService.java
> 250217 userscontroller 오류해결

- src/main/resources/templates/index.html
> 250217 어드민 이동

- src/main/resources/application.properties
> 250217 디비 연결 오류 해결

- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/java/pocopoco_vplay/admin/model/mapper/AdminMapper.java
- src/main/java/pocopoco_vplay/admin/model/service/AdminService.java
- src/main/java/pocopoco_vplay/admin/model/vo/PageInfo.java
- src/main/java/pocopoco_vplay/commom/Pagination.java
- src/main/resources/mappers/admin-mapper.xml
- src/main/resources/templates/views/admin/users_management.html
> 250217 user list 불러오기 진행 중

- src/main/java/pocopoco_vplay/users/model/mapper/UsersMapper.java
- src/main/java/pocopoco_vplay/users/model/service/UsersService.java
> 250217 권태혁의 바보같은 실수 ><

- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/java/pocopoco_vplay/users/model/vo/Users.java
- src/main/resources/templates/views/users/signup.html
> 250219 users model.vo 수정

- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/resources/static/css/topbar.css
- src/main/resources/templates/index.html
- src/main/resources/templates/views/common/topbar.html
- src/main/resources/templates/views/myPage/creator_page.html
- src/main/resources/templates/views/myPage/my_account.html
- src/main/resources/templates/views/myPage/my_downloads.html
- src/main/resources/templates/views/myPage/my_favorites.html
- src/main/resources/templates/views/myPage/my_inquiry.html
- src/main/resources/templates/views/myPage/my_payments.html
- src/main/resources/templates/views/users/signIn.html
- src/main/resources/templates/views/users/signup.html
> 20250219 수정

- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/java/pocopoco_vplay/admin/model/mapper/AdminMapper.java
- src/main/java/pocopoco_vplay/admin/model/service/AdminService.java
- src/main/java/pocopoco_vplay/board/model/vo/Content.java
- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/resources/mappers/admin-mapper.xml
- src/main/resources/templates/views/admin/inquiry_management.html
- src/main/resources/templates/views/common/topbar.html
> 250219 로그아웃 수정 및 어드민 진행 중

- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/java/pocopoco_vplay/admin/model/mapper/AdminMapper.java
- src/main/java/pocopoco_vplay/admin/model/service/AdminService.java
- src/main/java/pocopoco_vplay/board/model/vo/Content.java
- src/main/resources/mappers/admin-mapper.xml
- src/main/resources/static/css/admin/admin_sidebar.css
- src/main/resources/templates/views/admin/admin_sidebar.html
- src/main/resources/templates/views/admin/inquiry_management.html
- src/main/resources/templates/views/admin/users_management.html
250219 Content 수정 및 Admin 기능 구현
> 250219 Content 수정 및 Admin 기능 구현

- src/main/resources/templates/views/users/find_id.html
- src/main/resources/templates/views/users/signup.html
> 아이디 찾기 중간 커밋(아직 미완료..)

- src/main/resources/mappers/admin-mapper.xml
- src/main/resources/templates/views/admin/managing_templates.html
> 250224 컨텐츠 게시물 목록 리스트 완료

- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/resources/static/css/user/sidebar.css
- src/main/resources/templates/views/common/topbar.html
- src/main/resources/templates/views/myPage/my_projects.html
- src/main/resources/templates/views/myPage/my_sidebar.html
- src/main/resources/templates/views/myPage/price.html
> 20250224 하는중

- src/main/resources/static/css/user/sidebar.css
- src/main/resources/templates/views/myPage/my_sidebar.html
> 풀 전 커밋 마이페이지

- src/main/resources/static/css/user/sidebar.css
- src/main/resources/templates/views/myPage/my_projects.html
- src/main/resources/templates/views/myPage/my_sidebar.html
> 마이페이지 사이드 바 css수정

- src/main/resources/static/css/topbar.css
- src/main/resources/templates/index.html
- src/main/resources/templates/views/common/topbar.html
> 20250224 topbar 수정

- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/java/pocopoco_vplay/admin/model/mapper/AdminMapper.java
- src/main/java/pocopoco_vplay/admin/model/service/AdminService.java
- src/main/resources/mappers/admin-mapper.xml
- src/main/resources/static/css/admin/users_management.css
- src/main/resources/templates/views/admin/managing_request_posts.html
- src/main/resources/templates/views/admin/users_management.html
> 250224 admin 수정

- src/main/resources/templates/views/users/signup.html
- src/main/resources/templates/views/users/signup_success.html
> 20250224 회원가입페이지 수정

- src/main/resources/static/css/user/myPage.css
- src/main/resources/static/css/user/sidebar.css
- src/main/resources/templates/views/myPage/my_account.html
- src/main/resources/templates/views/myPage/my_downloads.html
- src/main/resources/templates/views/myPage/my_favorites.html
- src/main/resources/templates/views/myPage/my_inquiry.html
- src/main/resources/templates/views/myPage/my_payments.html
- src/main/resources/templates/views/myPage/my_projects.html
- src/main/resources/templates/views/myPage/my_sidebar.html
> 20250224 myPage css 등등 수정

- src/main/resources/templates/views/myPage/my_favorites.html
- src/main/resources/templates/views/myPage/my_projects.html
- src/main/resources/templates/views/myPage/my_sidebar.html
> 250225 사이드바 수정

- src/main/resources/templates/views/myPage/my_favorites.html
- src/main/resources/templates/views/myPage/my_projects.html
> my favorite 수정

- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/java/pocopoco_vplay/admin/model/mapper/AdminMapper.java
- src/main/java/pocopoco_vplay/admin/model/service/AdminService.java
- src/main/resources/mappers/admin-mapper.xml
- src/main/resources/templates/views/admin/admin_sidebar.html
- src/main/resources/templates/views/admin/inquiry_management.html
- src/main/resources/templates/views/admin/users_management.html
> 250225 회원 관리 및 inquiry 관리

- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/java/pocopoco_vplay/users/model/mapper/UsersMapper.java
- src/main/java/pocopoco_vplay/users/model/service/UsersService.java
- src/main/resources/mappers/users-mapper.xml
- src/main/resources/templates/views/myPage/my_sidebar.html
> 20250225 사이드바 정보 가져오기

- src/main/resources/mappers/users-mapper.xml
- src/main/resources/templates/views/myPage/my_account.html
- src/main/resources/templates/views/users/find_id_success.html
- src/main/resources/templates/views/users/signup.html
> 20250225 My Account 수정중

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/vo/Content.java
- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/mappers/users-mapper.xml
- src/main/resources/templates/views/myPage/my_favorites.html
- src/main/resources/templates/views/myPage/my_projects.html
좋아요 목록 , 좋아요 갯수 , 조회수 ,(myProjects)
목록 가져오고 카테고리 별로 나눠서 동적으로 화면에 뿌려줌
> 좋아요 목록 , 좋아요 갯수 , 조회수 ,(myFavorites)

- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/java/pocopoco_vplay/admin/model/mapper/AdminMapper.java
- src/main/java/pocopoco_vplay/admin/model/service/AdminService.java
- src/main/resources/mappers/admin-mapper.xml
- src/main/resources/templates/views/admin/dashboard.html
- src/main/resources/templates/views/admin/inquiry_management.html
- src/main/resources/templates/views/admin/managing_request_posts.html
- src/main/resources/templates/views/admin/managing_templates.html
- src/main/resources/templates/views/admin/users_management.html
> 250225 google 차트 진행 중

- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/java/pocopoco_vplay/users/model/mapper/UsersMapper.java
- src/main/java/pocopoco_vplay/users/model/service/UsersService.java
- src/main/resources/mappers/users-mapper.xml
- src/main/resources/templates/views/myPage/my_account.html
- src/main/resources/templates/views/users/signup.html
> 20250225 회원정보수정 수정중

- src/main/java/pocopoco_vplay/users/model/service/UsersService.java
> 250226 } 누가 뺐냐 ㅋㅋ 죽을래?

- src/main/resources/mappers/board-mapper.xml
- src/main/resources/mappers/users-mapper.xml
> 쿼리 완료 정렬 완료

- src/main/java/pocopoco_vplay/users/model/service/UsersService.java
> service 수정

- src/main/java/pocopoco_vplay/users/controller/UsersController.java
> 비밀번호 확인 재수정

- src/main/resources/templates/views/admin/dashboard.html
> 250227 차트 수정 중

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/java/pocopoco_vplay/commom/TemplateResolverConfig.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/static/css/board/all_menu.css
- src/main/resources/templates/views/board/content/all_menu.html
> 전체리스트 뿌리기 진행

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/commom/TemplateResolverConfig.java
- src/main/resources/templates/views/board/content/GraphicTemplates/GraphicTemplates_list.html
- src/main/resources/templates/views/board/content/all_menu.html
- src/main/resources/templates/views/board/content/fonts/fonts_list.html
- src/main/resources/templates/views/board/content/music/music_list.html
- src/main/resources/templates/views/board/content/photo/photo-list.html
- src/main/resources/templates/views/board/content/stockVideo/stock-video_list.html
- src/main/resources/templates/views/common/topbar.html
> 250303 리스트 뿌려주기 진행 중

- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/mappers/board-mapper.xml
250304 board-mapper inquiry 수정
> 250304 board-mapper inquiry 수정

- src/main/resources/mappers/board-mapper.xml
> 250304 board오류 수정

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/inquiry/inquiry_writer.html
- src/main/resources/templates/views/board/request/request_detail.html
- src/main/resources/templates/views/board/request/request_list.html
- src/main/resources/templates/views/myPage/my_favorites.html
> 250304 의뢰 작성 완료

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/static/css/board/videoTemplates/detail.css
- src/main/resources/static/css/board/videoTemplates/list.css
- src/main/resources/templates/views/board/content/all_menu.html
- src/main/resources/templates/views/board/content/videoTemplates/videoTemplates_detail.html
- src/main/resources/templates/views/board/content/videoTemplates/videoTemplates_list.html
> 250304 올메뉴 및 디테일 페이지 작업 진행 중

- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/java/pocopoco_vplay/users/model/service/UsersService.java
- src/main/resources/templates/views/myPage/my_payments.html
> 20250304 내 결제정보 수정중

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/mappers/board-mapper.xml
> 문의 종류 수정 추가

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/application.properties
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/content/all_menu.html
> 250307 좋아요 기능

- src/main/resources/mappers/board-mapper.xml
> 250309 오류 수정

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/resources/templates/index.html
- src/main/resources/templates/views/board/content/all_menu.html
> 250309 html 추가 및 오류 수정

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/inquiry/inquiry_detail.html
- src/main/resources/templates/views/board/inquiry/inquiry_update.html
> 20250307 답변 추가

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
> 250310 오류 수정

- src/main/java/pocopoco_vplay/board/model/vo/Content.java
- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/resources/templates/views/myPage/my_inquiry.html
> my inquiry 답변대기 답변완료 상태표시 추가

- build.gradle
- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/resources/application.properties
> 20250310삭제완룡

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/resources/templates/views/board/inquiry/inquiry_detail.html
- src/main/resources/templates/views/board/inquiry/inquiry_update.html
- src/main/resources/templates/views/board/inquiry/inquiry_writer.html
- src/main/resources/templates/views/myPage/my_account.html
- src/main/resources/templates/views/myPage/my_inquiry.html
- src/main/resources/templates/views/myPage/my_payments.html
- src/main/resources/templates/views/myPage/price.html
- src/main/resources/templates/views/users/signIn.html
- src/main/resources/templates/views/users/signup.html
> 20250310 이것 저것 수정

- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/java/pocopoco_vplay/users/model/mapper/UsersMapper.java
- src/main/resources/mappers/users-mapper.xml
> 아이디 찾기 커밋용 푸쉬

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/application.properties
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/request/request_detail.html
> 20250310 댓글작성완료

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/resources/templates/views/board/content/videoTemplates/videoTemplates_list.html
> 250310 카테고리 처리

- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/myPage/my_commission.html
- src/main/resources/templates/views/myPage/price.html
> 내 의뢰 내역 가져오기 수정완료

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/request/request_detail.html
- src/main/resources/templates/views/board/request/request_write.html
> 20250312 댓글 수정 완료

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/request/request_detail.html
- src/main/resources/templates/views/board/request/request_write.html
> 20250312 댓글 삭제 완료

- src/main/resources/templates/views/board/request/request_detail.html
> 20250312 수정하다가 원래대로 돌리기~

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/request/request_list.html
> 250313 리스트 동기 처리

- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/java/pocopoco_vplay/admin/model/mapper/AdminMapper.java
- src/main/java/pocopoco_vplay/admin/model/service/AdminService.java
- src/main/resources/mappers/admin-mapper.xml
- src/main/resources/static/css/admin/admin_page.css
- src/main/resources/templates/views/admin/management_inquiry.html
> 20250314 관리자 문의 리스트 필터

- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/java/pocopoco_vplay/admin/model/mapper/AdminMapper.java
- src/main/java/pocopoco_vplay/admin/model/service/AdminService.java
- src/main/resources/mappers/admin-mapper.xml
- src/main/resources/templates/views/admin/admin_sidebar.html
- src/main/resources/templates/views/admin/management_inquiry.html
- src/main/resources/templates/views/admin/management_request.html
- src/main/resources/templates/views/admin/management_templates.html
관리자 페이지 템플릿 관리, 의뢰 게시물 관리 필터링 추가
> 관리자 페이지 템플릿 관리, 의뢰 게시물 관리 필터링 추가

- build.gradle
- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/resources/templates/views/board/request/edit_request.html
- src/main/resources/templates/views/board/request/request_detail.html
- src/main/resources/templates/views/board/request/request_list.html
- src/main/resources/templates/views/board/request/request_write.html
> 20250316 썸머노트 이용한 글쓰기

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/resources/templates/views/board/content/videoTemplates/video-templates_list.html
- src/main/resources/templates/views/board/request/request_list.html
> 250316 진행 중

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
> 20250316 썸머노트 이용한 글쓰기 컨트롤러 수정

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/inquiry/inquiry_detail.html
- src/main/resources/templates/views/board/inquiry/inquiry_update.html
- src/main/resources/templates/views/board/inquiry/inquiry_write.html
- src/main/resources/templates/views/board/request/edit_request.html
- src/main/resources/templates/views/board/request/request_list.html
- src/main/resources/templates/views/board/request/request_write.html
> 250317 의뢰 게시판 검색 기능

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/content/videoTemplates/video-templates_list.html
> 250316 작업 진행 중

- .gitignore
> 250317 gitignore

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/java/pocopoco_vplay/board/model/vo/Content.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/content/content_write.html
- src/main/resources/templates/views/board/content/videoTemplates/video-templates_list.html
- src/main/resources/templates/views/myPage/my_projects.html
> 250317 컨텐츠 글쓰기 진행 중

- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/java/pocopoco_vplay/admin/model/mapper/AdminMapper.java
- src/main/java/pocopoco_vplay/admin/model/service/AdminService.java
- src/main/resources/mappers/admin-mapper.xml
- src/main/resources/templates/views/admin/management_request.html
- src/main/resources/templates/views/admin/management_templates.html
- src/main/resources/templates/views/admin/management_users.html
> 관리자 페이지 검색 완벽완

- src/main/resources/templates/views/myPage/my_projects.html
> 250318 my_page 수정

- src/main/resources/templates/views/board/content/content_write.html
- src/main/resources/templates/views/myPage/my_trash.html
> 250320 휴지통 수정

- src/main/resources/static/css/admin/admin_page.css
- src/main/resources/static/css/admin/dashboard.css
- src/main/resources/static/css/board/all_menu.css
- src/main/resources/static/css/rBoard/requestBoard.css
- src/main/resources/static/css/user/myPage.css
- src/main/resources/templates/views/board/request/request_list.html
- src/main/resources/templates/views/myPage/my_downloads.html
- src/main/resources/templates/views/myPage/my_projects.html
> 20250320 css 수정

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/static/css/admin/admin_page.css
- src/main/resources/templates/index.html
- src/main/resources/templates/views/admin/management_templates.html
> 20250320 MD추천 화면구현 완료

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/content/content_write.html
- src/main/resources/templates/views/board/content/videoTemplates/video-templates_detail.html
> 250321 content글 등록 완료

- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/resources/static/css/topbar.css
- src/main/resources/templates/views/common/topbar.html
- src/main/resources/templates/views/myPage/license.html
- src/main/resources/templates/views/users/my_message.html
> license 추가

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/java/pocopoco_vplay/board/model/vo/Files.java
- src/main/java/pocopoco_vplay/cloudflare/model/service/R2Service.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/content/videoTemplates/video-templates_detail.html
- src/main/resources/templates/views/board/content/videoTemplates/video-templates_list.html
> 250321 다운로드 완료

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/content/content_update.html
- src/main/resources/templates/views/board/content/videoTemplates/video-templates_detail.html
> 250321 수정 페이지 진행 중

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/content/videoTemplates/video-templates_detail.html
> 250322  다운로드 기록 완료

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/mapper/BoardMapper.java
- src/main/java/pocopoco_vplay/board/model/service/BoardService.java
- src/main/java/pocopoco_vplay/board/model/vo/Files.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/mappers/users-mapper.xml
- src/main/resources/templates/views/board/content/content_update.html
- src/main/resources/templates/views/board/content/content_write.html
- src/main/resources/templates/views/board/content/videoTemplates/video-templates_detail.html
250323 수정 페이지 추가 및 기능 완료, files 테이블 컬럼 추가
> 250323 수정 페이지 추가 및 기능 완료, files 테이블 컬럼 추가

- src/main/resources/templates/views/users/my_message.html
> 20250324 쪽지 수정

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/resources/templates/views/board/content/content_list.html
> 250324 템플릿 리스트 수정

- src/main/resources/templates/views/board/content/content_detail.html
> 250324 템플릿 옆에 바 수정

- src/main/resources/mappers/users-mapper.xml
> 카카오 로그인 프로필 수정

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/java/pocopoco_vplay/cloudflare/model/service/R2Service.java
- src/main/resources/application.properties
> 250324 다운로드 수정

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/java/pocopoco_vplay/home/controller/HomeController.java
- src/main/resources/mappers/admin-mapper.xml
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/static/css/board/all_menu.css
- src/main/resources/static/css/board/videoTemplates/list.css
- src/main/resources/templates/index.html
- src/main/resources/templates/views/admin/dashboard.html
- src/main/resources/templates/views/admin/management_templates.html
- src/main/resources/templates/views/board/content/content_list.html
- src/main/resources/templates/views/board/content/content_update.html
- src/main/resources/templates/views/board/content/content_write.html
- src/main/resources/templates/views/myPage/my_projects.html
> 250325 자잘한 기능 수정 완료

- src/main/resources/static/css/user/myPage.css
- src/main/resources/templates/views/myPage/my_downloads.html
- src/main/resources/templates/views/myPage/my_favorites.html
- src/main/resources/templates/views/myPage/my_projects.html
- src/main/resources/templates/views/myPage/my_trash.html
> 20250325 마이페이지 css 완벽 수정

- src/main/resources/templates/views/myPage/my_projects.html
> 마이페이지 디테일 페이지 들어가기 수정

- src/main/resources/templates/views/common/topbar.html
- src/main/resources/templates/views/myPage/my_inquiry.html
20250325 탑바 쪽지 색상 변경 및 마이페이지 의뢰 삭제 수정
> 20250325 탑바 쪽지 색상 변경 및 마이페이지 의뢰 삭제 수정

- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/board/model/vo/Reply.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/templates/views/board/request/request_detail.html
> 20250325 덮기용 푸쉬

- src/main/resources/templates/views/board/request/request_detail.html
> 20250325 댓글 수정 완료

- src/main/resources/templates/index.html
- src/main/resources/templates/views/board/request/request_detail.html
> 20250325 댓글 삭제 진행중 커밋

- src/main/java/pocopoco_vplay/board/model/vo/Content.java
- src/main/resources/mappers/users-mapper.xml
- src/main/resources/static/css/user/myPage.css
- src/main/resources/static/css/user/sidebar.css
- src/main/resources/templates/views/board/request/request_detail.html
- src/main/resources/templates/views/common/topbar.html
- src/main/resources/templates/views/myPage/price.html
- src/main/resources/templates/views/users/my_message.html
20250325 의뢰게시판 수정 및 나머지 css 수정
> 20250325 의뢰게시판 수정 및 나머지 css 수정

- src/main/resources/mappers/board-mapper.xml
- src/main/resources/mappers/users-mapper.xml
- src/main/resources/static/css/board/content_list.css
- src/main/resources/static/css/user/myPage.css
- src/main/resources/templates/index.html
- src/main/resources/templates/views/board/content/all_menu.html
- src/main/resources/templates/views/board/content/content_list.html
- src/main/resources/templates/views/myPage/my_projects.html
> 250326 마이페이지 수정

- src/main/resources/templates/views/board/request/request_detail.html
> 댓글 이미지 불러오기 수정

- src/main/java/pocopoco_vplay/ajax/controller/AjaxController.java
- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/static/css/board/content_list.css
- src/main/resources/templates/index.html
- src/main/resources/templates/views/board/content/content_detail.html
- src/main/resources/templates/views/board/content/content_list.html
> 250326 list 오류 수정

- src/main/resources/static/css/common.css
- src/main/resources/static/css/index.css
- src/main/resources/templates/views/board/content/all_menu.html
> 20250325 중간 커밋

- src/main/resources/static/css/board/all_menu.css
- src/main/resources/templates/views/board/content/all_menu.html
- src/main/resources/templates/views/board/content/content_list.html
> 250326 allmenu 끝

- src/main/resources/static/css/board/content_list.css
- src/main/resources/templates/views/myPage/subscribe.html
> 20250325 마이페이지 구독 목록 css수정

- src/main/resources/static/css/board/content_list.css
> 템플릿 리스트 글자 갯수 제한

- src/main/java/pocopoco_vplay/home/controller/HomeController.java
- src/main/java/pocopoco_vplay/users/model/vo/Users.java
- src/main/resources/templates/index.html
- src/main/resources/templates/views/board/content/content_list.html
- src/main/resources/templates/views/users/createrPage.html
> 250327 음악 페이지 수정 및 구독 기능 추가

- src/main/resources/templates/views/board/inquiry/inquiry_detail.html
> 문의 디테일 가운데 정렬 해제

- src/main/resources/templates/index.html
> 250327 메인페이지 수정

- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/resources/mappers/admin-mapper.xml
> 관리자 문의 달기 수정

- src/main/resources/templates/views/myPage/my_sidebar.html
> 250327 오류 수정

- src/main/resources/templates/views/myPage/my_commission.html
> 250327 커미션 수정

- build.gradle
- src/main/java/pocopoco_vplay/admin/controller/AdminController.java
- src/main/java/pocopoco_vplay/admin/model/mapper/AdminMapper.java
- src/main/java/pocopoco_vplay/admin/model/service/AdminService.java
- src/main/java/pocopoco_vplay/board/controller/BoardController.java
- src/main/java/pocopoco_vplay/commom/config/Mailconfig.java
- src/main/java/pocopoco_vplay/users/controller/UsersController.java
- src/main/java/pocopoco_vplay/users/model/mapper/UsersMapper.java
- src/main/java/pocopoco_vplay/users/model/service/UsersService.java
- src/main/resources/application.properties
- src/main/resources/mappers/admin-mapper.xml
- src/main/resources/mappers/board-mapper.xml
- src/main/resources/mappers/payment-mapper.xml
- src/main/resources/mappers/users-mapper.xml
- src/main/resources/static/css/admin/dashboard.css
- src/main/resources/templates/index.html
- src/main/resources/templates/views/admin/dashboard.html
- src/main/resources/templates/views/board/content/content_list.html
1. 메인 화면 구독 누를 시 구독자 변화 실시간 반영
2. 자신의 계정 구독 못함 + 알림창으로 구독못한다는 창 추가
3. 대쉬보드 그래프 제거
4. 대쉬보드 총 금액 추가
> Develop 250930 수정사항
